version: '3'

services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis-data:/data
    command: redis-server

  bot:
    image: euberdeveloper/tumi-app-bot:latest
    restart: always
    env_file:
      - ./config/bot.env
    depends_on:
      - redis

  watchtower:
    image: containrrr/watchtower:latest
    env_file:
      - ./config/watchtower.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  redis-data:
