name: Lint

on: [push]

jobs:
  lint:
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
          node-version: [18.x]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node dependencies
        run: npm install
        
      - name: Lint code
        run: npm run lint